MvcSupportApp/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcSupportApp.Models
{
    public class Ticket
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [MaxLength(60)]
        public string Title { get; set; }
        [Required]
        //[DataType(DataType.Date)]
        [Display(Name = "Created date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Created { get; set; } = DateTime.Now;
        [Required]
        //[DataType(DataType.Date)]
        [Display(Name = "Due date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Due { get; set; } = DateTime.Now.AddDays(10);
        [Required]
        public bool IsOpen { get; set; }
        //true - ticket is open
        //false - ticket is closed
        public double diff => (DateTime.Now - this.Due ).TotalHours;

    }
}

MvcSupportApp/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcSupportApp.Models
{
    public class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
    }
}

MvcSupportApp/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MvcSupportApp.Models;
using MvcSupportApp.Data;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Interfaces;

namespace MvcSupportApp.Controllers
{
    public class TicketController : Controller
    {

        //private readonly TicketContext _context;

        ////using dependency injection
        //public TicketController(TicketContext context)
        //{
        //    _context = context;
        //}

        //Property of the type IRepository <TEnt>
        private IRepository<Ticket> _repository;

        //The Dependency Injection of the IRepository<TEnt>
        public TicketController(IRepository<Ticket> repo)
        {
            _repository = repo;
        }

        /// <summary>
        /// GET: Tickets, Gets all tickets from the list
        /// </summary>
        /// <returns>List of tickets</returns>
        public ActionResult Index()
        {
            var ticks =  _repository.All.Where(x => x.IsOpen == true).OrderBy(x => x.Due);
            return View(ticks);
            //return View(await _repository.Tickets.Where(x => x.IsOpen == true).OrderBy(x => x.Due).ToListAsync());
        }


        /// <summary>
        /// GET: Create ticket view
        /// </summary>
        /// <returns>A form to create ticket</returns>
        public ActionResult Create()
        {
            //Get the ticket from ticketList sample collection for demo purpose.
            //You can get the ticket from the database in the real application 
            //var tick = ticketList.Where(s => s.Id == TicketId).FirstOrDefault();
            Ticket tick = new Ticket();
            return View(tick);
        }

        /// <summary>
        /// POST: Ticket, Creates new ticket
        /// </summary>
        /// <returns>Index view, if all correct</returns>
        [HttpPost]
        public ActionResult Create(Ticket tick)
        {
            var  tickTmp = new Ticket
            {
                Title = tick.Title,
                Created = tick.Created,
                Due = tick.Due,
                IsOpen = true
            };

            if (ModelState.IsValid)
            {
                //write code to update ticket 
                //_context.Tickets.Add(tickTmp);
                //_context.SaveChanges();
                //return RedirectToAction("Index");
                _repository.Add(tickTmp);
                return RedirectToAction("Index");
            }
            return View(tickTmp);
        }

        /// <summary>
        /// GET: Ticket, Deletes a ticket with id
        /// </summary>
        /// <returns>Index view, if all correct</returns>
        [HttpGet]
        [Route("Ticket/Close/{tickID:int}")]
        public IActionResult Close(int tickId)
        {
            //var tickTmp =  _context.Tickets.First(m => m.Id == tickId);
            var tickTmp2 = _repository.Get(tickId);
            if (tickTmp2 == null)
            {
                return NotFound();
            }
            tickTmp2.IsOpen = false;

            _repository.Update(tickTmp2);
            return RedirectToAction("Index");
            //_context.Tickets.Update(tickTmp);
            //_context.SaveChanges();
            //return RedirectToAction("Index");
        }
    }
}

MvcSupportApp/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicketApp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Ticket" asp-action="Index" class="navbar-brand">TicketApp</a>
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Ticket" asp-action="Index">Tickets</a></li>
                </ul>
            </div>*@
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - TicketApp</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

MvcSupportApp/Views/Ticket/Create.cshtml
@model MvcSupportApp.Models.Ticket
@{
    ViewBag.Title = "Create ticket";
}

<h2>Create ticket</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Due, htmlAttributes: new { @class= "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Due, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Due, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcSupportApp/Views/Ticket/Index.cshtml
@model IEnumerable<MvcSupportApp.Models.Ticket>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Due)
        </th>
        <th>
            Action
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr @(( item.diff > -1) ?  "class=danger "  : "")>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Due)
            </td>
            <td>
                @Html.ActionLink("Close", "Close", new { id = item.Id })
            </td>
        </tr>
    }

</table>